name: Send Bluesky Post

on:
    [push]

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: myConsciousness/bluesky-post@v5
        with:
          text: "A new version of Curl Browser has been uploaded to https://github.com/wish13yt/curlbrowser! This was an automated message sent from GitHub Workflows."
          identifier: ${{ secrets.BLUESKY_IDENTIFIER }}
          password: ${{ secrets.BLUESKY_PASSWORD }}
